"""Fetch Twemoji and write the mod's emoji images and lookup table.

    python tools/fetch_twemoji.py [--tag v17.0.3] [--size 32]

Takes the 72x72 PNGs from jdecked/twemoji (the maintained Twemoji, as used by Discord),
leaves out the skin-tone variants (about half the set; src/ap/emoji.cpp shows those in the
default tone), scales the rest to --size, and writes:
  res/emoji/<codepoints>.png    served to the UI as mod://<mod id>/res/emoji/<codepoints>.png
  res/emoji/LICENSE.txt         the CC-BY 4.0 attribution the graphics require
  src/ap/emoji_table.inc        every sequence we have an image for, for src/ap/emoji.cpp

Needs git and Pillow. Run it again to update to a newer Twemoji; commit the results.
"""
import argparse
import io
import os
import shutil
import subprocess
import sys
import tempfile

from PIL import Image

REPO = "https://github.com/jdecked/twemoji.git"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "res", "emoji")
TABLE = os.path.join(ROOT, "src", "ap", "emoji_table.inc")

LICENSE = """Emoji graphics: Twemoji {tag}, https://github.com/jdecked/twemoji
Copyright 2019 Twitter, Inc and other contributors; 2024 onward jdecked and contributors.
Licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/
Scaled to {size}x{size} for the Dusklight Archipelago mod, skin-tone variants left out;
otherwise unchanged.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="v17.0.3")
    ap.add_argument("--size", type=int, default=32)
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(["git", "clone", "--quiet", "--depth", "1", "--branch", args.tag,
                        "--filter=blob:none", "--sparse", REPO, tmp], check=True)
        subprocess.run(["git", "-C", tmp, "sparse-checkout", "set", "assets/72x72"], check=True)
        src = os.path.join(tmp, "assets", "72x72")
        skin_tones = ("1f3fb", "1f3fc", "1f3fd", "1f3fe", "1f3ff")
        names = sorted(f[:-4] for f in os.listdir(src) if f.endswith(".png")
                       and not any(t in f[:-4].split("-") for t in skin_tones))

        if os.path.isdir(OUT_DIR):
            shutil.rmtree(OUT_DIR)
        os.makedirs(OUT_DIR)
        total = 0
        for name in names:
            im = Image.open(os.path.join(src, name + ".png")).convert("RGBA")
            im = im.resize((args.size, args.size), Image.LANCZOS)
            out = os.path.join(OUT_DIR, name + ".png")
            im.save(out, optimize=True)
            total += os.path.getsize(out)

    with io.open(os.path.join(OUT_DIR, "LICENSE.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write(LICENSE.format(tag=args.tag, size=args.size))
    with io.open(TABLE, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"// Generated by tools/fetch_twemoji.py from Twemoji {args.tag}: every emoji\n"
                "// sequence res/emoji/ has an image for, as lowercase hex codepoints joined by '-'.\n")
        for name in names:
            f.write(f'"{name}",\n')
    print(f"{len(names)} emoji, {total / 1e6:.1f} MB at {args.size}px -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
